name = "barberking"
main = "src/index.js"
compatibility_date = "2026-01-01"

[assets]
directory = "."
binding = "ASSETS"
not_found_handling = "404-page"

[[d1_databases]]
binding = "DB"
database_name = "barberking"
database_id = "2598b929-32b4-4ee2-b96a-a8cefeef02c1"

[triggers]
crons = ["0 * * * *"]
